# Configuration file for LSTM Iron Ore Forecasting Model
# All hyperparameters and settings centralized here per PRD requirements

# Data configuration - file paths and preprocessing settings
data:
  # Input data file (contains 12 features + Y target variable)
  consolidated_features: "data/processed/consolidated_features_y.pkl"

  # Output directories for results
  results_dir: "results"
  plots_dir: "results/plots"
  models_dir: "results/models"

# Feature selection - configure which features to use for training/testing
# Available features from consolidated dataset:
features:
  - "price_65_m1" # Continuous M+1 65% iron ore futures price
  - "price_62_m1" # Continuous M+1 62% iron ore futures price
  - "Ukraine Concentrate fines" # Ukraine concentrate fines pricing
  - "lump premium" # Iron ore lump premium
  # - "IOCJ Import margin" # IOCJ import margin
  - "rebar steel margin " # Rebar steel margin (note: trailing space in original data)
  # - "indian pellet premium" # Indian pellet premium
  - "(IOCJ+SSF)/2-PBF" # Combined index calculation
  - "62 Index" # 62% grade index
  - "65 Index" # 65% grade index
  # - "IOCJ Inventory" # IOCJ inventory levels (weekly, forward-filled)
  - "IOCJ Weekly shipment" # IOCJ weekly shipment volumes (weekly, forward-filled)

# Model architecture hyperparameters
model:
  # Number of time steps in each input sequence for LSTM
  sequence_length: 12

  # Number of hidden units in LSTM layers
  hidden_size: 8

  # Number of stacked LSTM layers
  number_of_layers: 2

  # Dropout rate for regularization (prevent overfitting)
  dropout_rate: 0.35

  # Use bidirectional LSTM (processes sequences forward and backward)
  bidirectional: true

  # Apply layer normalization for training stability
  layer_norm: true

# Training configuration
training:
  # Number of samples per training batch
  batch_size: 32

  # Learning rate for Adam optimizer
  learning_rate: 0.0005

  # Maximum number of training epochs
  epochs: 70

  # Early stopping patience (stop if no validation improvement for N epochs)
  early_stopping_patience: 12

  # Gradient clipping norm to prevent exploding gradients
  gradient_clip_norm: 0.3 # 1.0 caused some unstability of losses in training

  # Loss function (Mean Squared Error for regression)
  loss_function: "mse" # NOT BEING USED

  # Optimizer type
  optimizer: "adam" # NOT BEING USED

# Data splitting ratios (chronological splits per PRD)
# Total period: March 30, 2022 - Present (868 valid samples)
splits:
  # Training set:
  train_ratio: 0.80

  # Validation set:
  val_ratio: 0.00

  # Test set:
  test_ratio: 0.20

# Feature scaling configuration
scaling:
  # Scale input features to [0,1] range using MinMaxScaler
  scale_features: true

  # Do NOT scale target variable (Y) - already percentage returns
  scale_target: false # NOT BEING USED

# Model evaluation metrics
metrics:
  # Root Mean Squared Error
  - "rmse"

  # Mean Absolute Error
  - "mae"

  # Directional Accuracy (% of correct directional predictions)
  - "directional_accuracy"

# Device configuration
device:
  # Use GPU if available, otherwise CPU
  use_cuda: true

# Training assessment thresholds
thresholds:
  # Performance assessment (validation loss improvement)
  plateau_tolerance: 0.001 # Minimum improvement to avoid "PLATEAU" status

  # Speed assessment (seconds per epoch)
  fast_epoch_time: 10 # Below this = "FAST"
  medium_epoch_time: 30 # Below this = "MEDIUM", above = "SLOW"

  # Total time assessment (seconds)
  quick_training_time: 300 # 5 minutes - Below this = "QUICK"
  moderate_training_time: 1800 # 30 minutes - Below this = "MODERATE", above = "LENGTHY"

  # Model complexity thresholds (parameter count)
  simple_model_params: 10000 # Below this = "SIMPLE"
  moderate_model_params: 100000 # Below this = "MODERATE", above = "COMPLEX"

  # Evaluation quality thresholds
  excellent_accuracy: 60 # Directional accuracy >= this = "EXCELLENT"
  good_accuracy: 55 # Directional accuracy >= this = "GOOD"
  fair_accuracy: 50 # Directional accuracy >= this = "FAIR", below = "POOR"

  strong_correlation: 0.5 # R² >= this = "STRONG"
  moderate_correlation: 0.2 # R² >= this = "MODERATE", below = "WEAK"

# DataLoader configuration
dataloader:
  # Number of worker processes for data loading (0 = main process only)
  num_workers: 0

# Data validation tolerances
validation:
  # Tolerance for split ratio validation (should sum to 1.0)
  split_ratio_tolerance: 0.01
